/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_SIOPAYLOAD_PB_H_INCLUDED
#define PB_SIOPAYLOAD_PB_H_INCLUDED
#include "nanopb/pb.h"

#include <stdbool.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ControlReceive { 
    bool dsr; 
    bool cts; 
} ControlReceive;

typedef struct _ControlSend { 
    bool dtr; 
    bool rts; 
} ControlSend;

typedef struct _DataReceive { 
    pb_callback_t data; 
    uint32_t length; 
} DataReceive;

typedef struct _DataSend { 
    pb_callback_t data; 
    uint32_t length; 
} DataSend;

typedef struct _SIOPayload { 
    pb_size_t which_type;
    union {
        DataReceive data_receive;
        DataSend data_send;
        ControlReceive control_receive;
        ControlSend control_send;
    } type; 
} SIOPayload;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ControlReceive_init_default              {0, 0}
#define ControlSend_init_default                 {0, 0}
#define DataReceive_init_default                 {{{NULL}, NULL}, 0}
#define DataSend_init_default                    {{{NULL}, NULL}, 0}
#define SIOPayload_init_default                  {0, {DataReceive_init_default}}
#define ControlReceive_init_zero                 {0, 0}
#define ControlSend_init_zero                    {0, 0}
#define DataReceive_init_zero                    {{{NULL}, NULL}, 0}
#define DataSend_init_zero                       {{{NULL}, NULL}, 0}
#define SIOPayload_init_zero                     {0, {DataReceive_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define ControlReceive_dsr_tag                   1
#define ControlReceive_cts_tag                   2
#define ControlSend_dtr_tag                      1
#define ControlSend_rts_tag                      2
#define DataReceive_data_tag                     1
#define DataReceive_length_tag                   2
#define DataSend_data_tag                        1
#define DataSend_length_tag                      2
#define SIOPayload_data_receive_tag              1
#define SIOPayload_data_send_tag                 2
#define SIOPayload_control_receive_tag           3
#define SIOPayload_control_send_tag              4

/* Struct field encoding specification for nanopb */
#define ControlReceive_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     dsr,               1) \
X(a, STATIC,   SINGULAR, BOOL,     cts,               2)
#define ControlReceive_CALLBACK NULL
#define ControlReceive_DEFAULT NULL

#define ControlSend_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     dtr,               1) \
X(a, STATIC,   SINGULAR, BOOL,     rts,               2)
#define ControlSend_CALLBACK NULL
#define ControlSend_DEFAULT NULL

#define DataReceive_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
#define DataReceive_CALLBACK pb_default_field_callback
#define DataReceive_DEFAULT NULL

#define DataSend_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
extern bool write_string(pb_ostream_t *stream, const pb_field_iter_t *field, void * const *arg);
#define DataSend_CALLBACK write_string
#define DataSend_DEFAULT NULL

#define SIOPayload_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,data_receive,type.data_receive),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,data_send,type.data_send),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,control_receive,type.control_receive),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,control_send,type.control_send),   4)
#define SIOPayload_CALLBACK NULL
#define SIOPayload_DEFAULT NULL
#define SIOPayload_type_data_receive_MSGTYPE DataReceive
#define SIOPayload_type_data_send_MSGTYPE DataSend
#define SIOPayload_type_control_receive_MSGTYPE ControlReceive
#define SIOPayload_type_control_send_MSGTYPE ControlSend

extern const pb_msgdesc_t ControlReceive_msg;
extern const pb_msgdesc_t ControlSend_msg;
extern const pb_msgdesc_t DataReceive_msg;
extern const pb_msgdesc_t DataSend_msg;
extern const pb_msgdesc_t SIOPayload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ControlReceive_fields &ControlReceive_msg
#define ControlSend_fields &ControlSend_msg
#define DataReceive_fields &DataReceive_msg
#define DataSend_fields &DataSend_msg
#define SIOPayload_fields &SIOPayload_msg

/* Maximum encoded size of messages (where known) */
/* DataReceive_size depends on runtime parameters */
/* DataSend_size depends on runtime parameters */
/* SIOPayload_size depends on runtime parameters */
#define ControlReceive_size                      4
#define ControlSend_size                         4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
