/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_SIOPAYLOAD_PB_H_INCLUDED
#define PB_SIOPAYLOAD_PB_H_INCLUDED
#include <nanopb/pb.h>
#include "sys/types.h"
#include "dirent.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DataTransfer { 
    pb_callback_t data; 
} DataTransfer;

typedef struct _FlowControl { 
    bool dxr; 
    bool xts; 
} FlowControl;

typedef struct _SIOPayload { 
    pb_callback_t cb_type;
    pb_size_t which_type;
    union {
        DataTransfer data_transfer;
        FlowControl flow_control;
    } type; 
} SIOPayload;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define FlowControl_init_default                 {0, 0}
#define DataTransfer_init_default                {{{NULL}, NULL}}
#define SIOPayload_init_default                  {{{NULL}, NULL}, 0, {DataTransfer_init_default}}
#define FlowControl_init_zero                    {0, 0}
#define DataTransfer_init_zero                   {{{NULL}, NULL}}
#define SIOPayload_init_zero                     {{{NULL}, NULL}, 0, {DataTransfer_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define DataTransfer_data_tag                    1
#define FlowControl_dxr_tag                      1
#define FlowControl_xts_tag                      2
#define SIOPayload_data_transfer_tag             1
#define SIOPayload_flow_control_tag              2

/* Struct field encoding specification for nanopb */
#define FlowControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     dxr,               1) \
X(a, STATIC,   SINGULAR, BOOL,     xts,               2)
#define FlowControl_CALLBACK NULL
#define FlowControl_DEFAULT NULL

#define DataTransfer_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1)
#define DataTransfer_CALLBACK pb_default_field_callback
#define DataTransfer_DEFAULT NULL

#define SIOPayload_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (type,data_transfer,type.data_transfer),   1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (type,flow_control,type.flow_control),   2)
#define SIOPayload_CALLBACK NULL
#define SIOPayload_DEFAULT NULL
#define SIOPayload_type_data_transfer_MSGTYPE DataTransfer
#define SIOPayload_type_flow_control_MSGTYPE FlowControl

extern const pb_msgdesc_t FlowControl_msg;
extern const pb_msgdesc_t DataTransfer_msg;
extern const pb_msgdesc_t SIOPayload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define FlowControl_fields &FlowControl_msg
#define DataTransfer_fields &DataTransfer_msg
#define SIOPayload_fields &SIOPayload_msg

/* Maximum encoded size of messages (where known) */
/* DataTransfer_size depends on runtime parameters */
/* SIOPayload_size depends on runtime parameters */
#define FlowControl_size                         4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
