/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "siopayload.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FlowControl, FlowControl, AUTO)


PB_BIND(DataTransfer, DataTransfer, AUTO)


PB_BIND(SIOPayload, SIOPayload, AUTO)



