/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "siopayload.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ControlReceive, ControlReceive, AUTO)


PB_BIND(ControlSend, ControlSend, AUTO)


PB_BIND(DataReceive, DataReceive, AUTO)


PB_BIND(DataSend, DataSend, AUTO)


PB_BIND(SIOPayload, SIOPayload, AUTO)



